name: Test Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          docker build -f Dockerfile.test -t hacs-plugins-tests .
          docker run --rm hacs-plugins-tests

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: false
          load: false
          tags: test-build
          cache-from: type=gha
          cache-to: type=gha,mode=max
